### ISSUE TITLE
Logging Stops After Start-Sleep

### ISSUE THREAD

**Issue by awickham10** [PowershellFrameworkCollective/psframework#254] opened 2018-11-29 18:40 UTC
It appears that Start-Sleep stops logging providers from logging any messages. The messages output to the console still but they do not show up in any of the logging providers (gelf or filesystem).

Script to reproduce
```powershell
Import-Module C:\SQL\Modules\PSFramework\0.10.28.144\PSFramework.psd1
$VerbosePreference = 'Continue'
Write-Host "Sleeping"
Write-PSFMessage -Level "Verbose" -Message "Sleeping"
Start-Sleep -Seconds 2
Write-Host "Done Sleeping"
Write-PSFMessage -Level "Verbose" -Message "Done Sleeping"
```

Command to reproduce
```powershell.exe -file .\test.ps1```

Output
```
Sleeping
VERBOSE: [13:38:38][test.ps1] Sleeping
Done Sleeping
VERBOSE: [13:38:40][test.ps1] Done Sleeping
VERBOSE: [13:38:40][Stop-PSFRunspace] Stopping runspace: psframework.logging
VERBOSE: [13:38:41][Stop-PSFRunspace] Stopping runspace: psframework.taskengine
```

**Comment by awickham10** [comment] 2018-11-29 18:42
P.S. This only happens when calling through powershell.exe. If I run the script in PowerShell with .\test.ps1 the logging providers work properly.

**Comment by FriedrichWeinmann** [comment] 2018-12-01 08:55
Thanks Andrew, this shouldn't be happening obviously.
Can't reproduce alas, at least not in my version of PSFramework (0.10.29.160) :(

Can you try it with the latest version?
If it still fails for you with the latest version, please send me a support package (Ideally via slack; `New-PSFSupportPackage`). Note that such a package will contain a lot of information about the computer it was generated from, you can customize which information to include using `-Include` and `-Exclude` depending on the level of information you can share.
Ideally generate it as part of the reproduction script.

**Comment by FriedrichWeinmann** [comment] 2019-02-07 06:27
Found the root-cause
The runspace termination event had a bug. Fixed in the latest release

**Closed by FriedrichWeinmann** 2019-02-07 06:27 UTC
Labels: Status: Pending, Type: Bug
