### ISSUE TITLE
Tab Completion Issue (1.0.33)

### ISSUE THREAD

**Issue by Rick-2CA** [PowershellFrameworkCollective/psframework#382] opened 2019-08-14 17:21 UTC
Using a [test module](https://gist.github.com/Rick-2CA/cc389f3372718da5ef8baf6af2554edb) the following tab completion/validation behavior was experienced:

In Psf 1.0.33 I don't get tab completion, but do get validation on HeaderColumn.
1.0.33 expected result is both tab completion and validation

In Psf 1.0.19 I get tab completion, but do not get validation.
1.0.19 expected result is tab completion and not validation (this scenario was addressed in 1.0.33)

The module will create a test file called TestData.csv.  Expected execution is to type out `Test-Function2 -InputFile TestData.csv -HeaderColumn` and be able to get tab completion on `HeaderColumn`.

**Comment by FriedrichWeinmann** [comment] 2019-08-25 23:47
Thanks for the thorough repro.
Should be resolved in 1.0.35
Root cause: A change in scriptblock handling would prevent the completion scriptblock to seethe automatic variables.

Please verify resolution on your end :)

**Comment by FriedrichWeinmann** [comment] 2019-08-26 16:11
Confirmed as resolved

**Closed by FriedrichWeinmann** 2019-08-26 16:11 UTC
Labels: Status: Resolved, Type: Bug
